In [1]:
import numpy as np
import pandas as pd
import os

In [11]:
image_dir = "/home/ubuntu/Desktop/CNNs"
dir_list = [x for x in os.walk(os.path.join(os.getcwd(), image_dir))][1:]
dir_list[1]

('/home/ubuntu/Desktop/CNNs/sample',
 [],
 ['16_right.jpeg',
  '15_right.jpeg',
  '16_left.jpeg',
  '13_left.jpeg',
  '17_left.jpeg',
  '17_right.jpeg',
  '15_left.jpeg',
  '10_left.jpeg',
  '13_right.jpeg',
  '10_right.jpeg'])

In [3]:
label = pd.read_csv("trainLabels.csv")
print "number of training set: %d" % len(label)
label.head()

number of training set: 35126


image  level
0   10_left      0
1  10_right      0
2   13_left      0
3  13_right      0
4   15_left      1

In [4]:
Class = {
    0: [1, 0, 0, 0, 0],
    1: [0, 1, 0, 0, 0],
    2: [0, 0, 1, 0, 0],
    3: [0, 0, 0, 1, 0],
    4: [0, 0, 0, 0, 1]
}

In [5]:
label["level"] = label["level"].map(Class)

In [6]:
label.head()

image            level
0   10_left  [1, 0, 0, 0, 0]
1  10_right  [1, 0, 0, 0, 0]
2   13_left  [1, 0, 0, 0, 0]
3  13_right  [1, 0, 0, 0, 0]
4   15_left  [0, 1, 0, 0, 0]

In [28]:
lab = dict(zip(label.image, label.level))

In [29]:
lab

{'29508_left': [1, 0, 0, 0, 0],
 '22905_left': [1, 0, 0, 0, 0],
 '18572_left': [1, 0, 0, 0, 0],
 '38420_left': [0, 0, 1, 0, 0],
 '40330_right': [1, 0, 0, 0, 0],
 '29921_left': [0, 1, 0, 0, 0],
 '21596_left': [1, 0, 0, 0, 0],
 '27273_right': [1, 0, 0, 0, 0],
 '31685_right': [1, 0, 0, 0, 0],
 '467_right': [1, 0, 0, 0, 0],
 '41804_left': [0, 1, 0, 0, 0],
 '13400_right': [1, 0, 0, 0, 0],
 '31034_left': [0, 0, 1, 0, 0],
 '36370_left': [1, 0, 0, 0, 0],
 '11304_left': [1, 0, 0, 0, 0],
 '5963_left': [1, 0, 0, 0, 0],
 '24510_left': [1, 0, 0, 0, 0],
 '16145_left': [1, 0, 0, 0, 0],
 '28731_left': [1, 0, 0, 0, 0],
 '32181_left': [1, 0, 0, 0, 0],
 '17962_right': [1, 0, 0, 0, 0],
 '33820_left': [0, 0, 1, 0, 0],
 '25629_right': [1, 0, 0, 0, 0],
 '11124_right': [1, 0, 0, 0, 0],
 '15993_left': [1, 0, 0, 0, 0],
 '38100_left': [0, 0, 1, 0, 0],
 '16693_right': [1, 0, 0, 0, 0],
 '2964_left': [1, 0, 0, 0, 0],
 '31324_right': [1, 0, 0, 0, 0],
 '13901_left': [1, 0, 0, 0, 0],
 '43959_left': [1, 0, 0, 0, 0],
 '

In [18]:
feature = []
target_class = []

for d in dir_list:
    for x in d[2]:
        print os.path.join(d[0], x)

/home/ubuntu/Desktop/CNNs/.ipynb_checkpoints/train_label-checkpoint.ipynb
/home/ubuntu/Desktop/CNNs/.ipynb_checkpoints/read_img-checkpoint.ipynb
/home/ubuntu/Desktop/CNNs/sample/16_right.jpeg
/home/ubuntu/Desktop/CNNs/sample/15_right.jpeg
/home/ubuntu/Desktop/CNNs/sample/16_left.jpeg
/home/ubuntu/Desktop/CNNs/sample/13_left.jpeg
/home/ubuntu/Desktop/CNNs/sample/17_left.jpeg
/home/ubuntu/Desktop/CNNs/sample/17_right.jpeg
/home/ubuntu/Desktop/CNNs/sample/15_left.jpeg
/home/ubuntu/Desktop/CNNs/sample/10_left.jpeg
/home/ubuntu/Desktop/CNNs/sample/13_right.jpeg
/home/ubuntu/Desktop/CNNs/sample/10_right.jpeg


In [41]:
feature

['16_right',
 '15_right',
 '16_left',
 '13_left',
 '17_left',
 '17_right',
 '15_left',
 '10_left',
 '13_right',
 '10_right']

In [46]:
target_class

[[0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0]]

In [20]:
import tensorflow as tf

In [48]:
y = tf.placeholder(tf.float32, shape=[None, 5])

In [50]:
with tf.Session() as sess:
    print sess.run(y, feed_dict={y:target_class})

[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [21]:
filename_queue = tf.train.string_input_producer("/home/ubuntu/Desktop/CNNs/train/sample/*.jpeg") #  list of files to read

reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)

my_img = tf.image.decode_png(value) # use png or jpg decoder based on your files.

init_op = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init_op)

# Start populating the filename queue.

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(coord=coord)

for i in range(1): #length of your filename list
    image = my_img.eval() #here is your image Tensor :) 

print(image.shape)
Image.show(Image.fromarray(np.asarray(image)))

coord.request_stop()
coord.join(threads)

ValueError: Shape () must have rank at least 1